[env:lgt]
platform = lgt8f
board = LGT8F328P

; change MCU frequency
board_build.f_cpu = 30000000L
build_flags =
	-Os
	-Wl,-u,vfprintf
	-Wl,-u,vfscanf
	-lprintf_flt
	-lscanf_flt
	-lm

lib_deps =
    https://github.com/b-oleg/LGT8FXP.git

upload_protocol = custom
upload_port = COM3
upload_speed = 115200
upload_flags =
    -p$BOARD_MCU
    -P$UPLOAD_PORT
    -B$UPLOAD_SPEED
    -cstk500v1
upload_command = avrdude.exe $UPLOAD_FLAGS -U flash:w:$SOURCE:i
